export const data = JSON.parse("{\"key\":\"v-9f83481e\",\"path\":\"/zh/news/hmily-2.0.2.html\",\"title\":\"Hmily发布2.0.2-RELEASE版本\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Hmily发布2.0.2-RELEASE版本\",\"author\":\"xiaoyu\",\"tags\":[\"hmily\"],\"date\":\"2019-04-05T00:00:00.000Z\",\"cover\":\"/assets/img/architecture/hmily-framework.png\",\"comment\":false,\"description\":\"Hmily 发布 2.0.2-RELEASE 版本\\r解决 SpringCloud 使用 hystrix 配置线程池策略的问题。; \\r新增对 springcloud 内嵌事务调用的问题。; \\r新增 Hmily 负载均衡策略。; \\r其他 bug 的修护，与代码的优化。; \\r去除不必须的第三方 jar 包。; \\r零侵入方式的引入。; Hmily 对现在流行 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/hmily-2.0.2.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Hmily发布2.0.2-RELEASE版本\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Hmily 发布 2.0.2-RELEASE 版本\\r解决 SpringCloud 使用 hystrix 配置线程池策略的问题。; \\r新增对 springcloud 内嵌事务调用的问题。; \\r新增 Hmily 负载均衡策略。; \\r其他 bug 的修护，与代码的优化。; \\r去除不必须的第三方 jar 包。; \\r零侵入方式的引入。; Hmily 对现在流行 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Hmily发布2.0.2-RELEASE版本\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"hmily\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-04-05T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Hmily发布2.0.2-RELEASE版本\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hmily-framework.png\\\"],\\\"datePublished\\\":\\\"2019-04-05T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Hmily 发布 2.0.2-RELEASE 版本\",\"slug\":\"hmily-发布-2-0-2-release-版本\",\"link\":\"#hmily-发布-2-0-2-release-版本\",\"children\":[]},{\"level\":2,\"title\":\"Hmily 对现在流行 RPC 框架以及 Spring 的支持情况。\",\"slug\":\"hmily-对现在流行-rpc-框架以及-spring-的支持情况。\",\"link\":\"#hmily-对现在流行-rpc-框架以及-spring-的支持情况。\",\"children\":[]},{\"level\":2,\"title\":\"Hmily 在 2.0.2 版本对使用者 RPC 集群时候负载均衡策略。\",\"slug\":\"hmily-在-2-0-2-版本对使用者-rpc-集群时候负载均衡策略。\",\"link\":\"#hmily-在-2-0-2-版本对使用者-rpc-集群时候负载均衡策略。\",\"children\":[]},{\"level\":2,\"title\":\"Hmily 的具体使用文档：\",\"slug\":\"hmily-的具体使用文档\",\"link\":\"#hmily-的具体使用文档\",\"children\":[]}],\"readingTime\":{\"minutes\":0.96,\"words\":289},\"filePathRelative\":\"zh/news/hmily-2.0.2.md\",\"localizedDate\":\"2019年4月5日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
