export const data = JSON.parse("{\"key\":\"v-5224044c\",\"path\":\"/zh/news/hutool-5.8.0.html\",\"title\":\"Hutool-5.8.0.M1 发布，尝试里程碑发布\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Hutool-5.8.0.M1 发布，尝试里程碑发布\",\"author\":\"hutool\",\"tags\":[\"hutool\"],\"date\":\"2022-03-30T00:00:00.000Z\",\"cover\":\"/assets/img/architecture/hutool-framework.png\",\"comment\":false,\"description\":\"Hutool 是一个小而全的 Java 工具类库，提供优雅、高效和便捷的工具方法。 Hutool 是什么 架构全景图 本来这个版本应该是 5.7.23 的，可惜用户提了一些 issue，这些问题的解决必须修改原有代码结构： 1. 如 MongoDB 客户端封装，由于其驱动本身做了不兼容修改，包装的工具类不得不进行修改。 2. 涉及到 Bean 拷贝的代...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/hutool-5.8.0.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Hutool-5.8.0.M1 发布，尝试里程碑发布\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Hutool 是一个小而全的 Java 工具类库，提供优雅、高效和便捷的工具方法。 Hutool 是什么 架构全景图 本来这个版本应该是 5.7.23 的，可惜用户提了一些 issue，这些问题的解决必须修改原有代码结构： 1. 如 MongoDB 客户端封装，由于其驱动本身做了不兼容修改，包装的工具类不得不进行修改。 2. 涉及到 Bean 拷贝的代...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hutool-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Hutool-5.8.0.M1 发布，尝试里程碑发布\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"hutool\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"hutool\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-03-30T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Hutool-5.8.0.M1 发布，尝试里程碑发布\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/hutool-framework.png\\\"],\\\"datePublished\\\":\\\"2022-03-30T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"hutool\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Hutool 是什么\",\"slug\":\"hutool-是什么\",\"link\":\"#hutool-是什么\",\"children\":[]},{\"level\":2,\"title\":\"5.8.0.M1\",\"slug\":\"_5-8-0-m1\",\"link\":\"#_5-8-0-m1\",\"children\":[{\"level\":3,\"title\":\"❌ 不兼容特性\",\"slug\":\"❌-不兼容特性\",\"link\":\"#❌-不兼容特性\",\"children\":[]},{\"level\":3,\"title\":\"🐣 新特性\",\"slug\":\"🐣-新特性\",\"link\":\"#🐣-新特性\",\"children\":[]},{\"level\":3,\"title\":\"🐞Bug 修复\",\"slug\":\"🐞bug-修复\",\"link\":\"#🐞bug-修复\",\"children\":[]}]},{\"level\":2,\"title\":\"社区共建\",\"slug\":\"社区共建\",\"link\":\"#社区共建\",\"children\":[]}],\"readingTime\":{\"minutes\":4.15,\"words\":1245},\"filePathRelative\":\"zh/news/hutool-5.8.0.md\",\"localizedDate\":\"2022年3月30日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
