export const data = JSON.parse("{\"key\":\"v-adf1a874\",\"path\":\"/zh/news/soul-1.0.4.html\",\"title\":\"Soul网关发布1.0.4-RELEASE版本\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Soul网关发布1.0.4-RELEASE版本\",\"author\":\"xiaoyu\",\"date\":\"2019-04-09T00:00:00.000Z\",\"tag\":[\"Soul\"],\"cover\":\"/assets/img/architecture/soul-framework.png\",\"comment\":false,\"description\":\"Soul 网关发布 1.0.4-RELEASE 版本\\r修复在 1.0.3 版本的后台管理中，出现的 bug。; \\r配置信息序列化方式支持自定义扩展。默认的序列化方式由 kroy 改为了 java 序列化方式。; \\rdubbo 框架支持的更改。; 对 dubbo 用户使用的更改。\\r在以前的版本中（1.0.2 or 1.0.3），dubbo 的参数是通过 ...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/news/soul-1.0.4.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Soul网关发布1.0.4-RELEASE版本\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Soul 网关发布 1.0.4-RELEASE 版本\\r修复在 1.0.3 版本的后台管理中，出现的 bug。; \\r配置信息序列化方式支持自定义扩展。默认的序列化方式由 kroy 改为了 java 序列化方式。; \\rdubbo 框架支持的更改。; 对 dubbo 用户使用的更改。\\r在以前的版本中（1.0.2 or 1.0.3），dubbo 的参数是通过 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Soul网关发布1.0.4-RELEASE版本\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2019-04-09T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Soul网关发布1.0.4-RELEASE版本\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/architecture/soul-framework.png\\\"],\\\"datePublished\\\":\\\"2019-04-09T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"Soul 网关发布 1.0.4-RELEASE 版本\",\"slug\":\"soul-网关发布-1-0-4-release-版本\",\"link\":\"#soul-网关发布-1-0-4-release-版本\",\"children\":[]},{\"level\":3,\"title\":\"对 dubbo 用户使用的更改。\",\"slug\":\"对-dubbo-用户使用的更改。\",\"link\":\"#对-dubbo-用户使用的更改。\",\"children\":[]},{\"level\":3,\"title\":\"关于使用 1.0.4 版本的建议。\",\"slug\":\"关于使用-1-0-4-版本的建议。\",\"link\":\"#关于使用-1-0-4-版本的建议。\",\"children\":[]},{\"level\":3,\"title\":\"如果您之前使用的 1.0.2 版本，想要更新到 1.0.4 版本。\",\"slug\":\"如果您之前使用的-1-0-2-版本-想要更新到-1-0-4-版本。\",\"link\":\"#如果您之前使用的-1-0-2-版本-想要更新到-1-0-4-版本。\",\"children\":[]},{\"level\":3,\"title\":\"遇到问题？\",\"slug\":\"遇到问题\",\"link\":\"#遇到问题\",\"children\":[]}],\"readingTime\":{\"minutes\":0.96,\"words\":289},\"filePathRelative\":\"zh/news/soul-1.0.4.md\",\"localizedDate\":\"2019年4月9日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
