export const data = JSON.parse("{\"key\":\"v-7ce29625\",\"path\":\"/awesome/\",\"title\":\"Awesome Dromara\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"Awesome Dromara\",\"sidebar\":false,\"breadcrumb\":false,\"pageInfo\":false,\"contributors\":false,\"editLink\":false,\"lastUpdated\":false,\"prev\":false,\"next\":false,\"comment\":false,\"description\":\"Idea Let every open source enthusiast, experience the joy of open source. Community Technology stack comprehensive open source co-build, maintain community neutrality, harmony a...\",\"head\":[[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/awesome/\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/awesome/\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Awesome Dromara\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Idea Let every open source enthusiast, experience the joy of open source. Community Technology stack comprehensive open source co-build, maintain community neutrality, harmony a...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Awesome Dromara\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[]}\"]]},\"headers\":[{\"level\":2,\"title\":\"Idea\",\"slug\":\"idea\",\"link\":\"#idea\",\"children\":[]},{\"level\":2,\"title\":\"Community\",\"slug\":\"community\",\"link\":\"#community\",\"children\":[]},{\"level\":2,\"title\":\"Website\",\"slug\":\"website\",\"link\":\"#website\",\"children\":[]},{\"level\":2,\"title\":\"Projects\",\"slug\":\"projects\",\"link\":\"#projects\",\"children\":[]},{\"level\":2,\"title\":\"Join\",\"slug\":\"join\",\"link\":\"#join\",\"children\":[]},{\"level\":2,\"title\":\"Responsibility\",\"slug\":\"responsibility\",\"link\":\"#responsibility\",\"children\":[]},{\"level\":2,\"title\":\"Code of Conduct\",\"slug\":\"code-of-conduct\",\"link\":\"#code-of-conduct\",\"children\":[]},{\"level\":2,\"title\":\"Project Donation\",\"slug\":\"project-donation\",\"link\":\"#project-donation\",\"children\":[]},{\"level\":2,\"title\":\"Support\",\"slug\":\"support\",\"link\":\"#support\",\"children\":[]},{\"level\":2,\"title\":\"Contact Us\",\"slug\":\"contact-us\",\"link\":\"#contact-us\",\"children\":[]}],\"readingTime\":{\"minutes\":2.41,\"words\":724},\"filePathRelative\":\"awesome/README.md\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
