export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"Project home","i":"home"},["/README.md"]],
  ["v-2e3eac9e","/slides.html",{"y":"s","t":"Slide page","i":"person-chalkboard"},[":md"]],
  ["v-0aa6c427","/activity/",{"y":"a","t":"Activity"},["/activity/README.md"]],
  ["v-7ce29625","/awesome/",{"y":"a","t":"Awesome Dromara"},["/awesome/README.md"]],
  ["v-145ac574","/blog/",{"y":"a","t":"Blog"},["/blog/README.md"]],
  ["v-685b5622","/blog/soul_source_learning_22_apache_dubbo.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"Disabling layout and features","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"Encryption Article","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown Enhance","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"Page Config","i":"file","O":1},[":md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"Features demo","i":"laptop-code"},["/demo/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"Guide","i":"lightbulb"},["/guide/README.md"]],
  ["v-1500d063","/news/",{"y":"a","t":"News"},["/news/README.md"]],
  ["v-6dc367c8","/projects/",{"y":"a","t":"Projects"},["/projects/README.md"]],
  ["v-2d0ad528","/zh/",{"y":"h","t":"首页"},["/zh/README.md"]],
  ["v-269ae70f","/zh/slides.html",{"y":"s","t":"幻灯片页","i":"person-chalkboard"},[":md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar feature","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo feature","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-1c782d50","/zh/activity/dromara-activites-introduce.html",{"y":"a","t":"Dromara 梦码读书会介绍"},[":md"]],
  ["v-583fae6e","/zh/activity/dromara-cloud-native-meet-02.html",{"y":"a","t":"Dromara Soul 源码01期阅读分享会02"},[":md"]],
  ["v-a74bd796","/zh/activity/dromara-cloud-native-meet.html",{"y":"a","t":"Dromara Soul源码01期阅读分享会01"},[":md"]],
  ["v-3100e6d8","/zh/activity/",{"y":"a","t":"活动"},["/zh/activity/README.md"]],
  ["v-4450d954","/zh/awesome/",{"y":"a","t":"Awesome Dromara"},["/zh/awesome/README.md"]],
  ["v-2b4be8a5","/zh/blog/",{"y":"a","t":"博客"},["/zh/blog/README.md"]],
  ["v-c2878338","/zh/blog/soul_source_learning_16_divide_sxj.html",{"y":"a","t":"Soul网关学习divide插件源码解读"},[":md"]],
  ["v-79eeff9c","/zh/blog/soul_source_learning_17_http.html",{"y":"a","t":"Soul网关学习Http请求探险"},[":md"]],
  ["v-92e572f6","/zh/blog/soul_source_learning_18_ratelimiter.html",{"y":"a","t":"Soul网关学习RateLimiter插件原理解析"},[":md"]],
  ["v-2a063bca","/zh/blog/soul_source_learning_19_redirect.html",{"y":"a","t":"Soul网关学习Redirect插件原理解析"},[":md"]],
  ["v-23b8cbd0","/zh/blog/soul_source_learning_20_sentinel.html",{"y":"a","t":"Soul网关学习Sentinel插件原理解析"},[":md"]],
  ["v-1fc031d4","/zh/blog/soul_source_learning_21_resilience4j.html",{"y":"a","t":"Soul网关学习Resilience4j插件原理解析"},[":md"]],
  ["v-552cbe11","/zh/blog/soul_source_learning_22_apache_dubbo.html",{"y":"a","t":"Soul网关学习Apache Dubbo插件原理解析"},[":md"]],
  ["v-c1942916","/zh/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-65c00218","/zh/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-36295574","/zh/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-62ced1a6","/zh/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-2b64e284","/zh/demo/",{"y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/zh/demo/README.md"]],
  ["v-47357bdb","/zh/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/zh/guide/README.md"]],
  ["v-9f83481e","/zh/news/hmily-2.0.2.html",{"y":"a","t":"Hmily发布2.0.2-RELEASE版本"},[":md"]],
  ["v-166ab031","/zh/news/hmily-2.1.1.html",{"y":"a","t":"时隔一年，dromara团队发布全新架构Hmily分布式事务的2.1.1版本"},[":md"]],
  ["v-2dae727a","/zh/news/hmily-restart.html",{"y":"a","t":"Hmily分布式事务重启月度报告"},[":md"]],
  ["v-5224044c","/zh/news/hutool-5.8.0.html",{"y":"a","t":"Hutool-5.8.0.M1 发布，尝试里程碑发布"},[":md"]],
  ["v-2bf1f394","/zh/news/",{"y":"a","t":"新闻"},["/zh/news/README.md"]],
  ["v-adf1a874","/zh/news/soul-1.0.4.html",{"y":"a","t":"Soul网关发布1.0.4-RELEASE版本"},[":md"]],
  ["v-793b5400","/zh/news/soul-2.1.x.html",{"y":"a","t":"Soul网关发布的2.1.X版本，到底有多方便？"},[":md"]],
  ["v-663f9427","/zh/news/soul-2.2.0.html",{"y":"a","t":"【Soul网关发布2.2.0】让高性能网关变得如此简单！"},[":md"]],
  ["v-210f2266","/zh/projects/",{"y":"a","t":"项目"},["/zh/projects/README.md"]],
  ["v-1e317375","/zh/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-763c1cd7","/zh/guide/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/zh/guide/bar/README.md"]],
  ["v-00fb7173","/zh/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-763e2284","/zh/guide/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/zh/guide/foo/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
]
