export const data = JSON.parse("{\"key\":\"v-685b5622\",\"path\":\"/blog/soul_source_learning_22_apache_dubbo.html\",\"title\":\"页面配置\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"页面配置\",\"icon\":\"file\",\"order\":1,\"author\":\"Ms.Hop\",\"date\":\"2020-01-01T00:00:00.000Z\",\"description\":\"目标\\rApache Dubbo 插件介绍; \\r元数据介绍; \\rApache Dubbo 插件配置; \\rBootstrap pom 配置; \\rsoul-admin 配置; \\rdubbo 服务 pom 配置; \\rApache Dubbo 泛化调用介绍; \\r通过 API 方式使用泛化调用; \\r通过 spring 使用泛化调用; \\r泛化调用实现流程; \\rSou...\",\"head\":[[\"link\",{\"rel\":\"alternate\",\"hreflang\":\"zh-cn\",\"href\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/blog/soul_source_learning_22_apache_dubbo.html\"}],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/soul_source_learning_22_apache_dubbo.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"页面配置\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"目标\\rApache Dubbo 插件介绍; \\r元数据介绍; \\rApache Dubbo 插件配置; \\rBootstrap pom 配置; \\rsoul-admin 配置; \\rdubbo 服务 pom 配置; \\rApache Dubbo 泛化调用介绍; \\r通过 API 方式使用泛化调用; \\r通过 spring 使用泛化调用; \\r泛化调用实现流程; \\rSou...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:locale:alternate\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Ms.Hop\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-01-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"页面配置\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-01-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Ms.Hop\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"目标\",\"slug\":\"目标\",\"link\":\"#目标\",\"children\":[{\"level\":3,\"title\":\"Apache Dubbo 插件介绍\",\"slug\":\"apache-dubbo-插件介绍\",\"link\":\"#apache-dubbo-插件介绍\",\"children\":[]},{\"level\":3,\"title\":\"Apache Dubbo 插件配置\",\"slug\":\"apache-dubbo-插件配置\",\"link\":\"#apache-dubbo-插件配置\",\"children\":[]},{\"level\":3,\"title\":\"Apache Dubbo 泛化调用介绍\",\"slug\":\"apache-dubbo-泛化调用介绍\",\"link\":\"#apache-dubbo-泛化调用介绍\",\"children\":[]},{\"level\":3,\"title\":\"Soul Dubbo 插件调用解析\",\"slug\":\"soul-dubbo-插件调用解析\",\"link\":\"#soul-dubbo-插件调用解析\",\"children\":[]},{\"level\":3,\"title\":\"Dubbo 泛化调用介绍\",\"slug\":\"dubbo-泛化调用介绍\",\"link\":\"#dubbo-泛化调用介绍\",\"children\":[]},{\"level\":3,\"title\":\"总结\",\"slug\":\"总结\",\"link\":\"#总结\",\"children\":[]},{\"level\":3,\"title\":\"参考\",\"slug\":\"参考\",\"link\":\"#参考\",\"children\":[]}]}],\"readingTime\":{\"minutes\":9.86,\"words\":2958},\"filePathRelative\":\"blog/soul_source_learning_22_apache_dubbo.md\",\"localizedDate\":\"January 1, 2020\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
