export const data = JSON.parse("{\"key\":\"v-a74bd796\",\"path\":\"/zh/activity/dromara-cloud-native-meet.html\",\"title\":\"Dromara Soul源码01期阅读分享会01\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Dromara Soul源码01期阅读分享会01\",\"author\":\"xiaoyu\",\"date\":\"2021-01-21T00:00:00.000Z\",\"tag\":[\"Soul\",\"Dromara\",\"Reactor\"],\"cover\":\"/assets/img/activities/dromara-open-soul-02.jpg\",\"comment\":false,\"description\":\"Dromara 线上活动 Dromara 源码阅读（Soul 2021 首次活动）\\r日期：2021 年 1 月 24 日，星期日; \\r时间：15:00 – 17:00; \\r地点：线上腾讯会议室; 活动详情 15:00 - 15:10 开场介绍梦码分享流程 by kimming & 崔 15:10 - 15:25 Soul 数据同步之 websocket...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/activity/dromara-cloud-native-meet.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Dromara Soul源码01期阅读分享会01\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Dromara 线上活动 Dromara 源码阅读（Soul 2021 首次活动）\\r日期：2021 年 1 月 24 日，星期日; \\r时间：15:00 – 17:00; \\r地点：线上腾讯会议室; 活动详情 15:00 - 15:10 开场介绍梦码分享流程 by kimming & 崔 15:10 - 15:25 Soul 数据同步之 websocket...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activities/dromara-open-soul-02.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Dromara Soul源码01期阅读分享会01\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Dromara\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Reactor\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-01-21T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Dromara Soul源码01期阅读分享会01\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activities/dromara-open-soul-02.jpg\\\"],\\\"datePublished\\\":\\\"2021-01-21T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"Dromara 源码阅读（Soul 2021 首次活动）\",\"slug\":\"dromara-源码阅读-soul-2021-首次活动\",\"link\":\"#dromara-源码阅读-soul-2021-首次活动\",\"children\":[]},{\"level\":3,\"title\":\"活动详情\",\"slug\":\"活动详情\",\"link\":\"#活动详情\",\"children\":[]}],\"readingTime\":{\"minutes\":0.79,\"words\":238},\"filePathRelative\":\"zh/activity/dromara-cloud-native-meet.md\",\"localizedDate\":\"2021年1月21日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
