export const data = JSON.parse("{\"key\":\"v-583fae6e\",\"path\":\"/zh/activity/dromara-cloud-native-meet-02.html\",\"title\":\"Dromara Soul 源码01期阅读分享会02\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"Dromara Soul 源码01期阅读分享会02\",\"author\":\"xiaoyu\",\"date\":\"2021-02-06T15:00:00.000Z\",\"tag\":[\"Soul\",\"Dromara\",\"Reactor\"],\"cover\":\"/assets/img/activities/dromara-open-soul-03.jpg\",\"comment\":false,\"description\":\"Dromara 线上活动 Dromara 源码阅读（Soul 2021 首次活动）\\r日期：2021 年 2 月 6 日，星期日; \\r时间：20:00 – 23:00; \\r地点：线上腾讯会议室; 活动详情 20:00 - 20:10 开场介绍近期梦码分享情况 by kimming & 崔 20:10 - 20:25 SPI 介绍以及 Soul SPI 如...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/zh/activity/dromara-cloud-native-meet-02.html\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Dromara Soul 源码01期阅读分享会02\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Dromara 线上活动 Dromara 源码阅读（Soul 2021 首次活动）\\r日期：2021 年 2 月 6 日，星期日; \\r时间：20:00 – 23:00; \\r地点：线上腾讯会议室; 活动详情 20:00 - 20:10 开场介绍近期梦码分享情况 by kimming & 崔 20:10 - 20:25 SPI 介绍以及 Soul SPI 如...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activities/dromara-open-soul-03.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Dromara Soul 源码01期阅读分享会02\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"xiaoyu\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Soul\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Dromara\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Reactor\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2021-02-06T15:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Dromara Soul 源码01期阅读分享会02\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/assets/img/activities/dromara-open-soul-03.jpg\\\"],\\\"datePublished\\\":\\\"2021-02-06T15:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"xiaoyu\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"Dromara 源码阅读（Soul 2021 首次活动）\",\"slug\":\"dromara-源码阅读-soul-2021-首次活动\",\"link\":\"#dromara-源码阅读-soul-2021-首次活动\",\"children\":[]},{\"level\":3,\"title\":\"活动详情\",\"slug\":\"活动详情\",\"link\":\"#活动详情\",\"children\":[]}],\"readingTime\":{\"minutes\":0.88,\"words\":264},\"filePathRelative\":\"zh/activity/dromara-cloud-native-meet-02.md\",\"localizedDate\":\"2021年2月6日\",\"autoDesc\":true,\"excerpt\":\"\"}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
